server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/agustinsaavedra2/PEP2_Tingeso
          search-paths: config-data
  application:
    name: config-service