apiVersion: v1
kind: PersistentVolume
metadata:
  name: discount-specialdays-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/discount-specialdays-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discount-specialdays-db-pvc
  labels:
    app: mysql
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-specialdays-db-deployment
  labels:
    app: discount-specialdays-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: discount-specialdays-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discount-specialdays-db-deployment
        tier: database
    spec:
      containers:
        - name: discount-specialdays-db
          image: mysql
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: discount-specialdays-db-data
      volumes:
        - name: discount-specialdays-db-data
          persistentVolumeClaim:
            claimName: discount-specialdays-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: discount-specialdays-db-service
  labels:
    app: discount-specialdays-db-service
    tier: database
spec:
  ports:
    - port: 3310
      targetPort: 3306
      protocol: TCP
  selector:
    app: discount-specialdays-db-deployment
    tier: database
  type: LoadBalancer