apiVersion: apps/v1
kind: Deployment
metadata: 
  name: discount-specialdays-service-deployment
  labels:
    app: discount-specialdays-service-deployment
spec: 
  selector:
    matchLabels: 
      app: discount-specialdays-service-deployment
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: discount-specialdays-service-deployment
    spec:
      containers:
        - name: discount-specialdays-service
          image: agustinsaavedra056/discount-specialdays-service
          ports: 
            - containerPort: 8094