apiVersion: apps/v1
kind: Deployment
metadata: 
  name: report-service-deployment
  labels:
    app: report-service-deployment
spec: 
  selector:
    matchLabels: 
      app: report-service-deployment
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: report-service-deployment
    spec:
      containers:
        - name: report-service
          image: agustinsaavedra056/report-service
          ports: 
            - containerPort: 8097