apiVersion: apps/v1
kind: Deployment
metadata: 
  name: weekly-rack-service-deployment
  labels:
    app: weekly-rack-service-deployment
spec: 
  selector:
    matchLabels: 
      app: weekly-rack-service-deployment
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: weekly-rack-service-deployment
    spec:
      containers:
        - name: weekly-rack-service
          image: agustinsaavedra056/weekly-rack-service
          ports: 
            - containerPort: 8096